
// Sample data for demonstration purposes
export const sampleExcelData = [
  {
    FirstParty: "ABC Corporation",
    FirstPartyNameEn: "ABC Corporation",
    FirstPartyNameAr: "شركة إيه بي سي",
    FirstPartyCRN: "1234567890",
    SecondParty: "XYZ Employer",
    SecondPartyNameEn: "XYZ Employer",
    SecondPartyNameAr: "شركة إكس واي زد للتوظيف",
    SecondPartyCRN: "0987654321",
    Promoter: "John Doe",
    PromoterNameEn: "John Doe",
    PromoterNameAr: "جون دو",
    PromoterID: "ID123456",
    Product: "Premium Smartphone",
    Location: "Shopping Mall - Riyadh"
  },
  {
    FirstParty: "Global Tech",
    FirstPartyNameEn: "Global Tech",
    FirstPartyNameAr: "جلوبال تك",
    FirstPartyCRN: "2345678901",
    SecondParty: "Staff Solutions",
    SecondPartyNameEn: "Staff Solutions",
    SecondPartyNameAr: "حلول التوظيف",
    SecondPartyCRN: "1098765432",
    Promoter: "Jane Smith",
    PromoterNameEn: "Jane Smith",
    PromoterNameAr: "جين سميث",
    PromoterID: "ID234567",
    Product: "Smart Watch",
    Location: "Electronics Store - Jeddah"
  },
  {
    FirstParty: "National Telecom",
    FirstPartyNameEn: "National Telecom",
    FirstPartyNameAr: "الاتصالات الوطنية",
    FirstPartyCRN: "3456789012",
    SecondParty: "Promoter Agency",
    SecondPartyNameEn: "Promoter Agency",
    SecondPartyNameAr: "وكالة الترويج",
    SecondPartyCRN: "2109876543",
    Promoter: "Mohammed Ahmed",
    PromoterNameEn: "Mohammed Ahmed",
    PromoterNameAr: "محمد أحمد",
    PromoterID: "ID345678",
    Product: "5G Internet Package",
    Location: "Telecom Center - Dammam"
  },
  {
    FirstParty: "Future Electronics",
    FirstPartyNameEn: "Future Electronics",
    FirstPartyNameAr: "إلكترونيات المستقبل",
    FirstPartyCRN: "4567890123",
    SecondParty: "Best Staffing",
    SecondPartyNameEn: "Best Staffing",
    SecondPartyNameAr: "أفضل التوظيف",
    SecondPartyCRN: "3210987654",
    Promoter: "Sarah Johnson",
    PromoterNameEn: "Sarah Johnson",
    PromoterNameAr: "سارة جونسون",
    PromoterID: "ID456789",
    Product: "Gaming Console",
    Location: "Department Store - Medina"
  },
  {
    FirstParty: "Luxury Brands",
    FirstPartyNameEn: "Luxury Brands",
    FirstPartyNameAr: "العلامات الفاخرة",
    FirstPartyCRN: "5678901234",
    SecondParty: "Elite HR",
    SecondPartyNameEn: "Elite HR",
    SecondPartyNameAr: "النخبة للموارد البشرية",
    SecondPartyCRN: "4321098765",
    Promoter: "Ali Hassan",
    PromoterNameEn: "Ali Hassan",
    PromoterNameAr: "علي حسن",
    PromoterID: "ID567890",
    Product: "Premium Perfume",
    Location: "Luxury Mall - Riyadh"
  }
];
