// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cysizbwsyuagbjwekdmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5c2l6YndzeXVhZ2Jqd2VrZG1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjQ3ODQsImV4cCI6MjA1OTYwMDc4NH0.YgQa2FxUQmL_gOylBFMyTsL8yseyOUQ_P7eCH0D4q8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);